---
title: "GDSC Cell Line Data Preprocessing"
author: "Seraphina Shi"
output:
  html_document:
    toc: true
    toc_float: true
---

```{r load_libs,  message=FALSE, warning=FALSE} 
library(here)
library(data.table)
library(readxl)
library(dplyr)
library(gtsummary)
library(stringr)
library(ggplot2)
# library(impute)
library(gplots)
```

```{r setup}
plotFolder <- here("images", "GDSC", "02_EDA")
if(!file.exists(plotFolder)) dir.create(plotFolder,recursive=TRUE)

dataFolder <- here("data", "GDSC")
if(!file.exists(dataFolder)) dir.create(dataFolder,recursive=TRUE)

knitr::opts_chunk$set(
  cache=FALSE, autodep=FALSE, warning=FALSE, message=FALSE, echo=TRUE,
  results = 'markup', dev='png', dpi=350, fig.align = "center", fig.path = paste0(plotFolder, "/"),
  cache.path=".cache/",
  duplicate.label="allow"
)

set.seed(234)
```


# load all data
## input data
### All cancer types
```{r load_data}
c_data <- read.csv(here(dataFolder, "c_data.csv"), row.names = 1)
c_meta <- read.csv(here(dataFolder, "c_meta.csv"))
d_data <- read.csv(here(dataFolder, "d_data.csv"), row.names = 1)
d_meta <- read.csv(here(dataFolder, "Drug_list2022.csv"))

cdr <- read.csv(here(dataFolder, "cdr.csv"), row.names = 1)
colnames(cdr) <- gsub("^X", "",  colnames(cdr))

cat("Cancer RNAseq data dim: ", dim(c_data))
cat("Drug PCA-based feature data dim: ", dim(d_data))
cat("CDR data dim: ", dim(cdr))
```

```{r cancer_type_counts, fig.height=4, fig.width=6}

c_type_levels = c("ALL", "LAML", "LCML", # leukemia
           "CLL", "DLBC", # lymphoma
           "MM",# blood, myeloma
           "LGG", # Brain Lower Grade Glioma 	胶质瘤, nervous_system
           "GBM", # Glioblastoma multiforme	多形成性胶质细胞瘤, nervous_system
           "MB", # nervous_system
           "NB", # neoblastoma 神经母细胞瘤
           "HNSC", # head & neck 头颈鳞状细胞癌
           "SKCM", # Skin Cutaneous Melanoma	皮肤黑色素瘤
           "BRCA", # breast
           "STAD", # Stomach adenocarcinoma	胃癌
           "ESCA", # Esophageal 食管癌
           "KIRC", # Kidney
           "LIHC", # liver
           "LUAD", "LUSC", # lung, lung_NSCLC
           "SCLC", # lung
           "MESO", # Mesothelioma 间皮瘤, lung
           "COAD/READ", # colon,
           "PAAD", # Pancreatic adenocarcinoma	胰腺癌
           "THCA", # Thyroid carcinoma	甲状腺癌, thyroid
           "OV", # Ovarian serous cystadenocarcinoma	卵巢浆液性囊腺癌, urogenital_system
           "UCEC", # Uterine Corpus Endometrial Carcinoma	子宫内膜癌, urogenital_system
           "PRAD", # Prostate adenocarcinoma	前列腺癌, urogenital_system
           "BLCA", # Bladder, urogenital_system
           "CESC" # Cervical squamous cell carcinoma and endocervical adenocarcinoma 宫颈鳞癌和腺癌, urogenital_system
           ) 

c_meta$cancer_type <- factor(c_meta$cancer_type, levels = c_type_levels)


c_type_color = c("#8B2323", "#FF4040", "#FF7256","#FFD300", "#F6FF00",  # leukemia, lymphoma
                 "#00FFE5",
                 "#5800FF", "#C100FF","#AB82FF", # nervous_system
                 "#CAFF70", "#FFB6C1", "#C1FFC1", "#FFB90F",  "#AEEEEE", "#FF83FA", "#9AFF9A", "#FFBBFF", 
                 "#007BFF",  "#4876FF", "#00BFFF", "#00E5FF", # lung
                 "#FF6A00", "#BFEFFF", "#FF6EB4",
                 "#00FF7B", "#C1FF00","#58FF00",  "#CAFF70", "#00FFB0", # urogenital_system
                 "grey")

names(c_type_color) = c(c_type_levels, "NA")

count_c_type_df <- data.frame("c_type" = factor(names(c_type_color), levels = names(c_type_color)),
                              "Freq"= c(as.numeric(table(c_meta$cancer_type)), sum(is.na(c_meta$cancer_type))),
                              "c_type_color" = c_type_color)

ggplot(count_c_type_df, aes(c_type, Freq, fill = c_type)) +
  geom_col() + 
  scale_x_discrete(limits=rev) + 
  coord_flip() + 
  scale_fill_manual(values = count_c_type_df$c_type_color) +
  theme_bw() + 
  theme(legend.position = "none") +
  labs(x = "Cancer type", y = "Frequency")
```

### Skin cancer
```{r}
set.seed(123)

c_types <- c("SKCM")

c_meta_skin <- c_meta[c_meta$cancer_type %in% c_types, ]
c_data_skin <- c_data[rownames(c_data) %in% c_meta_skin$COSMIC_ID, ]
cdr_skin <- cdr[rownames(cdr) %in% c_meta_skin$COSMIC_ID, ]

c_colors_skin <- rep(count_c_type_df$c_type_color[count_c_type_df$c_type %in% c_types], count_c_type_df$Freq[count_c_type_df$c_type %in% c_types])

```

## output data

```{r}
version_folder = "skin"
cdr_hat <- read.csv(here(dataFolder, version_folder, "GDSC_skin_cdr_hat.csv"), row.names = 1)
c_latent_0 <- read.csv(here(dataFolder, version_folder, "GDSC_skin_c_latent_cluster1.csv"), row.names = 1)
d_latent_0 <- read.csv(here(dataFolder, version_folder, "GDSC_skin_d_latent_cluster1.csv"), row.names = 1)

subcluster = T

if(subcluster) {
  c_latent_1 <- read.csv(here(dataFolder, version_folder, "GDSC_skin_c_latent_cluster2.csv"), row.names = 1)
  d_latent_1 <- read.csv(here(dataFolder, version_folder, "GDSC_skin_d_latent_cluster2.csv"), row.names = 1)
}

c_cluster <- cdr_hat[,c('c_name', 'c_cluster')] %>% unique()
d_cluster <- cdr_hat[,c('d_name', 'd_cluster')] %>% unique()
cd_cluster <-  cdr_hat[,c('c_name', 'd_name', 'cluster')] %>% unique()
```


```{r}
c_names_0 <- as.character(c_cluster$c_name[c_cluster$c_cluster == "0"])
if(subcluster) {
  c_names_01 <- as.character(c_cluster$c_name[c_cluster$c_cluster == "0 & 1"])
  c_names_1 <- as.character(c_cluster$c_name[c_cluster$c_cluster == "1"])
}
c_names_other <- as.character(c_cluster$c_name[c_cluster$c_cluster == -1])

d_names_0 <- as.character(d_cluster$d_name[d_cluster$d_cluster == "0"])
if(subcluster) {
  d_names_01 <- as.character(d_cluster$d_name[d_cluster$d_cluster == "0 & 1"])
  d_names_1 <- as.character(d_cluster$d_name[d_cluster$d_cluster == "1"])
}
d_names_other <- as.character(d_cluster$d_name[d_cluster$d_cluster == -1])

c_names = c(c_names_0, c_names_01, c_names_1, c_names_other)
d_names = c(d_names_0, d_names_01, d_names_1, d_names_other)
```

```{r}
library(reshape2)
cdr_hat_wide = dcast(cdr_hat, c_name ~ d_name, value.var = "cdr_hat")
  # reshape(cdr_hat[, c("c_name", "d_name", "cdr_hat")], idvar = "c_name", timevar = "d_name", direction = "wide")

rownames(cdr_hat_wide) = cdr_hat_wide$c_name
cdr_hat_wide = subset(cdr_hat_wide, select = -c_name)

cdr_hat_wide
```

# Summary table
## Cancer
```{r}
c_meta_skin = c_meta[c_meta$COSMIC_ID %in% c(c_names_0, c_names_01, c_names_1, c_names_other), ]
c_meta_skin$cluster = "Other"
c_meta_skin$cluster[c_meta_skin$COSMIC_ID %in% c_names_0] = "0"
c_meta_skin$cluster[c_meta_skin$COSMIC_ID %in% c_names_1] = "1"
c_meta_skin$cluster[c_meta_skin$COSMIC_ID %in% c_names_01] = "01"

library(table1)
# table1(~ factor(tissue_descriptor) + factor(tissue_descriptor_1) + factor(tissue_descriptor_2) + 
#          factor(tissue) + factor(tissue_status) + factor(sample_site) +
#          factor(cancer_type) + factor(cancer_type_passports) +
#          factor(gender) + factor(ethnicity) + age_at_sampling | cluster, data=c_meta_skin)


table1(~ factor(tissue) + factor(tissue_status) + factor(sample_site) + factor(cancer_type)  | cluster, data=c_meta_skin)


table1(~ factor(gender) + factor(ethnicity) + age_at_sampling | cluster, data=c_meta_skin)

# table1(~ factor(family_history_of_cancer) + factor(colorectal_cancer_risk_factors) +
#          factor(smoking_status) + alcohol_exposure_intensity + alcohol_consumption_per_week +
#          factor(history_diabetes) + factor(diabetes_treatment)| cluster, data=c_meta_skin)
```

## Drug
```{r}
d_meta_skin = d_meta[d_meta$Drug.Id %in% c(d_names_0, d_names_01, d_names_1, d_names_other), ]
d_meta_skin$cluster = "Other"
d_meta_skin$cluster[d_meta_skin$Drug.Id %in% d_names_0] = "0"
d_meta_skin$cluster[d_meta_skin$Drug.Id %in% d_names_1] = "1"
d_meta_skin$cluster[d_meta_skin$Drug.Id %in% d_names_01] = "01"

table1(~ factor(Target.pathway) | cluster, data=d_meta_skin)
table1(~factor(Targets) | cluster, data=d_meta_skin)
```

# EDA

## cdr
```{r}
make_cdr_heatmap <- function(x, rowColor, colColor, Rowv, Colv, binary=T){
  
  if(binary){
    col_cdr = c("red", "green")
    key_show = F
  } else {
    col_cdr = colorRampPalette(c("red",  "white",  "green"))(n = 20)
    key_show = T
  }
  
  
  heatmap_cdr <- heatmap.2(
    x,
    Rowv = Rowv,  # perform hierarchical clustering on rows
    Colv = Colv,  # Perform hierarchical clustering on columns
    col = col_cdr,  # Use the custom binary colors
    dendrogram = "both",
    trace = "none",
    key = key_show,  # Disable the default color key
    RowSideColors = rowColor,
    ColSideColors = colColor,
    labRow = FALSE,  # Hide row names
    labCol = FALSE,  # Hide column names
    main = "Cancer Drug Response",
    lwid = c(0.2, 5),
    lhei = c(1, 5)
  )
  
  # Add legend after creating the heatmap
  legend(y=1.15, x=0.0, xpd=TRUE, legend = c("0", "1"), fill = c("red", "green"), bty = "n", cex = 0.8, title = "Sensitivity")
  
  mtext("Cance\n Types", side = 2, line = 0.5, at = 1, las = 2, cex = 0.8)
  
  return(heatmap_cdr)
}
```

```{r skin_cdr_heatmap_hier0, fig.height=6, fig.width=10}
if(subcluster) {
    cdr_tmp = as.matrix(cdr_skin[c_names, d_names])

    cdr_row_color = c(rep("lightgreen", length(c_names_0)), rep("lightblue", length(c_names_01)),
              rep("khaki1", length(c_names_1)),  rep("lightgrey", length(c_names_other)))
    cdr_col_color = c(rep("lightgreen", length(d_names_0)), rep("lightblue", length(d_names_01)),
              rep("khaki1", length(d_names_1)),  rep("lightgrey", length(d_names_other)))
  
} else{
  cdr_tmp = as.matrix(cdr_skin[c(c_names_0, c_names_other), c(d_names_0, d_names_other)])

  cdr_row_color = c(rep("lightgreen", length(c_names_0)), rep("lightgrey", length(c_names_other)))
  cdr_col_color = c(rep("lightgreen", length(d_names_0)), rep("lightgrey", length(d_names_other)))
  
}

cdr_heatmap = make_cdr_heatmap(cdr_tmp, cdr_row_color, cdr_col_color, T, T)
```


```{r skin_cdr_heatmap, fig.height=6, fig.width=10}
cdr_heatmap_hier = make_cdr_heatmap(cdr_tmp, cdr_row_color, cdr_col_color, F, F)
```

## cdr hat
```{r skin_cdr_hat_heatmap, fig.height=6, fig.width=10}
if(subcluster) {
    cdr_hat_tmp = as.matrix(cdr_hat_wide[c_names, d_names])
} else{
  cdr_hat_tmp = as.matrix(cdr_hat[c(c_names_0, c_names_other), c(d_names_0, d_names_other)])
}

# cdr_hat_heatmap = make_cdr_heatmap(cdr_hat_tmp, cdr_row_color, cdr_col_color, F, F, binary = F)


  cdr_hat_heatmap <- heatmap.2(
    cdr_hat_tmp,
    Rowv = F,  # perform hierarchical clustering on rows
    Colv = F,  # Perform hierarchical clustering on columns
    col = colorRampPalette(c("red",  "white",  "green"))(n = 20),  # Use the custom binary colors
    dendrogram = "both",
    trace = "none",
    key = T,  # Disable the default color key
    RowSideColors = cdr_row_color,
    ColSideColors = cdr_col_color,
    labRow = FALSE,  # Hide row names
    labCol = FALSE,  # Hide column names
    main = "Cancer Drug Response"
    # lwid = c(0.2, 5),
    # lhei = c(1, 5)
  )
  
  mtext("Cance\n Types", side = 2, line = 0.5, at = 1, las = 2, cex = 0.8)
```

## c_data
```{r}
get_hclust_ind <- function(x){
  Rowv <- rowMeans(x, na.rm = T)
  hcr <- hclust(dist(x))
  ddr <- as.dendrogram(hcr)
  ddr <- reorder(ddr, Rowv)
  Ind <- order.dendrogram(ddr)
  
  return(Ind)
}

```

```{r c_data_heatmap, fig.width=10, fig.height=6}

# rowInd_data_0 = get_hclust_ind(as.matrix(c_data_skin[c_names_0, ]))
# rowInd_data_other = get_hclust_ind( as.matrix(c_data_skin[c_names_other, ]) )
# c_data_tmp = as.matrix(c_data_skin[c(c_names_0[rowInd_data_0], c_names_other[rowInd_data_other]), ])

c_data_tmp = as.matrix(c_data_skin[c_names, ])


heatmap_c_data <- heatmap.2(c_data_tmp,  # Exclude non-numeric columns
                         Rowv = F,  # Do not perform hierarchical clustering on rows
                         Colv = T,  # perform hierarchical clustering on columns
                         col = colorRampPalette(c("blue", "purple", "white", "orange", "red"))(n = 299),  # Apply custom colors to heatmap
                         dendrogram = "both",  # show dendrograms
                         trace = "none",  # Do not show trace
                         key = T,  # Show color key
                         RowSideColors = cdr_row_color,  # Row annotation color
                         labRow = T,  # Hide row names
                         labCol = F,  # Hide column names
                         main = "Cancer preprocessed RNAseq Data"
                         )

```

## c_latent
```{r c_latent_0_heatmap, fig.width=10, fig.height=6}
c_latent0_tmp = as.matrix(c_latent_0[c_names, ])

heatmap_c_data <- heatmap.2(c_latent0_tmp,  # Exclude non-numeric columns
                         Rowv = F,  # Do not perform hierarchical clustering on rows
                         Colv = T,  # perform hierarchical clustering on columns
                         col = colorRampPalette(c("blue", "purple", "white", "orange", "red"))(n = 299),  # Apply custom colors to heatmap
                         dendrogram = "both",  # show dendrograms
                         trace = "none",  # Do not show trace
                         key = T,  # Show color key
                         RowSideColors = cdr_row_color,  # Row annotation color
                         labRow = T,  # Hide row names
                         labCol = F,  # Hide column names
                         main = "Cancer Latent Data"
                         )

```
```{r c_latent_1_heatmap, fig.width=10, fig.height=6}
if(subcluster) {
  c_latent1_tmp = as.matrix(c_latent_1[c_names, ])

  heatmap_c_data <- heatmap.2(c_latent1_tmp,  # Exclude non-numeric columns
                           Rowv = F,  # Do not perform hierarchical clustering on rows
                           Colv = T,  # perform hierarchical clustering on columns
                           col = colorRampPalette(c("blue", "purple", "white", "orange", "red"))(n = 299),  # Apply custom colors to heatmap
                           dendrogram = "both",  # show dendrograms
                           trace = "none",  # Do not show trace
                           key = T,  # Show color key
                           RowSideColors = cdr_row_color,  # Row annotation color
                           labRow = T,  # Hide row names
                           labCol = F,  # Hide column names
                           main = "Cancer Latent Data"
                           )
}


```

## d_data
```{r d_data_heatmap, fig.width=10, fig.height=6}
d_data_tmp = as.matrix(d_data[d_names, ])


heatmap_d_data <- heatmap.2(d_data_tmp,  # Exclude non-numeric columns
                         Rowv = F,  # Do not perform hierarchical clustering on rows
                         Colv = T,  # perform hierarchical clustering on columns
                         col = colorRampPalette(c("blue", "purple", "white", "orange", "red"))(n = 299),  # Apply custom colors to heatmap
                         dendrogram = "both",  # show dendrograms
                         trace = "none",  # Do not show trace
                         key = T,  # Show color key
                         RowSideColors = cdr_col_color,  # Row annotation color
                         labRow = T,  # Hide row names
                         labCol = F,  # Hide column names
                         main = "Drug PCA Data"
                         )

```

## d_latent
```{r d_latent_heatmap, fig.width=10, fig.height=6}
d_latent_0_tmp = as.matrix(d_latent_0[d_names, ])


heatmap_d_latent0 <- heatmap.2(d_latent_0_tmp,  # Exclude non-numeric columns
                         Rowv = F,  # Do not perform hierarchical clustering on rows
                         Colv = T,  # perform hierarchical clustering on columns
                         col = colorRampPalette(c("blue", "purple", "white", "orange", "red"))(n = 299),  # Apply custom colors to heatmap
                         dendrogram = "both",  # show dendrograms
                         trace = "none",  # Do not show trace
                         key = T,  # Show color key
                         RowSideColors = cdr_col_color,  # Row annotation color
                         labRow = T,  # Hide row names
                         labCol = F,  # Hide column names
                         main = "Drug Latent Data"
                         )

```

```{r d_latent1_heatmap, fig.width=10, fig.height=6}
if(subcluster) {
  d_latent_1_tmp = as.matrix(d_latent_1[d_names, ])
  
  
  heatmap_d_latent1 <- heatmap.2(d_latent_1_tmp,  # Exclude non-numeric columns
                           Rowv = F,  # Do not perform hierarchical clustering on rows
                           Colv = T,  # perform hierarchical clustering on columns
                           col = colorRampPalette(c("blue", "purple", "white", "orange", "red"))(n = 299),  # Apply custom colors to heatmap
                           dendrogram = "both",  # show dendrograms
                           trace = "none",  # Do not show trace
                           key = T,  # Show color key
                           RowSideColors = cdr_col_color,  # Row annotation color
                           labRow = T,  # Hide row names
                           labCol = F,  # Hide column names
                           main = "Drug Latent Data"
                           )
}
```
